name: Projet push
# Le workflow va se déclencher à chaque push de mon application
on:
  push:
    branches:
      - main
      - dev
jobs:
  build_and_test:
    name: Build & test
    runs-on: ubuntu-latest
    steps:
      - name: Récup appli
        uses: actions/checkout@v4
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean install
      - name: Test with Maven
        run: mvn test
        continue-on-error: false # Le job échouera si les tests échouent
      - name: Upload build artifact
        if: ${{ success() && github.ref == 'refs/heads/main' }}
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: target/

  download:
    runs-on: ubuntu-latest
    needs: build_and_test
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Récupérer l'artéfact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: target/
      - name: Lister les fichiers
        run: ls target

  docker:
    runs-on: ubuntu-latest
    needs: download
    if: ${{ github.ref == 'refs/heads/main' }}
    env:
      USERNAME: ${{ secrets.DOCKER_USERNAME }}
      TOKEN: ${{ secrets.DOCKER_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: docker build -t $USERNAME/my_java_app .

      - name: Push Docker image
        run: docker push $USERNAME/my_java_app

#      - name: Test Docker image
#        run: |
#          docker pull $USERNAME/my_java_app
#          docker run --rm $USERNAME/my_java_app