name: Projet push
# Le workflow va se déclencher à chaque push de mon application
on: push
jobs:
  mon_job:
    name: Build & test
    runs-on: ubuntu-latest
    steps:
      - name: Récup appli
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean install
      - name: Test with Maven
        run: mvn test